package com.mercotrace.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class BusinessCategoryAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBusinessCategoryAllPropertiesEquals(BusinessCategory expected, BusinessCategory actual) {
        assertBusinessCategoryAutoGeneratedPropertiesEquals(expected, actual);
        assertBusinessCategoryAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBusinessCategoryAllUpdatablePropertiesEquals(BusinessCategory expected, BusinessCategory actual) {
        assertBusinessCategoryUpdatableFieldsEquals(expected, actual);
        assertBusinessCategoryUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBusinessCategoryAutoGeneratedPropertiesEquals(BusinessCategory expected, BusinessCategory actual) {
        assertThat(actual)
            .as("Verify BusinessCategory auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBusinessCategoryUpdatableFieldsEquals(BusinessCategory expected, BusinessCategory actual) {
        assertThat(actual)
            .as("Verify BusinessCategory relevant properties")
            .satisfies(a -> assertThat(a.getCategoryName()).as("check categoryName").isEqualTo(expected.getCategoryName()))
            .satisfies(a -> assertThat(a.getIsActive()).as("check isActive").isEqualTo(expected.getIsActive()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()))
            .satisfies(a -> assertThat(a.getUpdatedAt()).as("check updatedAt").isEqualTo(expected.getUpdatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBusinessCategoryUpdatableRelationshipsEquals(BusinessCategory expected, BusinessCategory actual) {
        // empty method
    }
}
